// apps/web/src/lib/components/forms/TextInput.svelte
<script lang="ts">
	import type { FieldElementProps } from "@formisch/svelte";

	interface Props extends FieldElementProps {
		class?: string;
		type: "text" | "email" | "tel" | "password" | "url" | "number" | "date";
		label?: string;
		placeholder?: string;
		required?: boolean;
		input: string | number | undefined;
		errors: [string, ...string[]] | null;
	}

	let { class: className, label, name, required, input, errors, ...fieldProps }: Props = $props();

	let value: string | number | undefined = $state();

	$effect(() => {
		if (!Number.isNaN(input)) {
			value = input;
		}
	});
</script>

<fieldset class="fieldset">
	<legend class="fieldset-legend">
		{label}
		{#if required}
			<span class="text-error">*</span>
		{/if}
	</legend>
	<input
		{...fieldProps}
		id={name}
		{name}
		class={[
			"input",
			{
				"input-error": errors,
			},
		]}
		{value}
		{required}
		aria-invalid={!!errors}
		aria-errormessage={`${name}-error`}
	/>
	{#if errors}
		<p class="label text-error">{errors[0]}</p>
	{/if}
</fieldset>

// src/lib/auth/client/components/TextInput.tsx
import type { FieldElementProps } from "@formisch/react";
import clsx from "clsx";

interface TextInputProps extends FieldElementProps {
	type: "text" | "email" | "tel" | "password" | "url" | "date";
	label?: string;
	placeholder?: string;
	input: string | undefined;
	errors: [string, ...string[]] | null;
	required?: boolean;
}

export function TextInput({ label, input, errors, ...props }: TextInputProps) {
	const { name, required } = props;
	return (
		<fieldset className="fieldset">
			<legend className="fieldset-legend">
				{label} {required && <span className="text-error">*</span>}
			</legend>
			<input
				{...props}
				id={name}
				name={name}
				className={clsx("input w-full", {
					"input-error": errors,
				})}
				required={required}
				value={input ?? ""}
				aria-invalid={!!errors}
				aria-errormessage={`${name}-error`}
			/>
			{errors && <p className="label text-error">{errors[0]}</p>}
		</fieldset>
	);
}
